using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wabbit.SourceGenerators
{
    /// <summary>
    /// Source generator for creating specialized game type enums from a base enum.
    /// </summary>
    [Generator]
    public class GameTypeEnumGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // Register a syntax receiver that will be created for each generation pass
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            // Get our syntax receiver
            if (!(context.SyntaxContextReceiver is SyntaxReceiver receiver))
                return;

            // Process each annotated enum
            foreach (var enumInfo in receiver.EnumsToAugment)
            {
                ProcessEnum(context, enumInfo);
            }
        }

        private void ProcessEnum(GeneratorExecutionContext context, EnumToAugment enumInfo)
        {
            var enumSymbol = enumInfo.EnumSymbol;
            var attributeData = enumInfo.AttributeData;
            var enumDeclaration = enumInfo.EnumDeclaration;

            // Extract prefixes from attribute
            var prefixes = attributeData.ConstructorArguments[0].Values
                .Select(arg => arg.Value?.ToString())
                .Where(prefix => !string.IsNullOrEmpty(prefix))
                .ToList();

            if (prefixes.Count == 0)
                return;

            var enumNamespace = enumSymbol.ContainingNamespace.ToDisplayString();
            var enumName = enumSymbol.Name;
            var enumMembers = enumSymbol.GetMembers().OfType<IFieldSymbol>()
                .Where(f => f.ConstantValue != null)
                .ToList();

            // Generate specialized enum for each prefix
            foreach (var prefix in prefixes)
            {
                var specializedEnumName = $"{prefix}GameType";
                var sourceCode = GenerateSpecializedEnum(enumNamespace, specializedEnumName, enumMembers);
                string fileName = $"{enumNamespace}.{specializedEnumName}.g.cs";
                context.AddSource(fileName, SourceText.From(sourceCode, Encoding.UTF8));
            }

            // Generate helper class
            var helpersSourceCode = GenerateHelperClass(enumNamespace, enumName, enumMembers, prefixes.Cast<string>().ToList());
            context.AddSource($"{enumNamespace}.GameTypeHelpers.g.cs", SourceText.From(helpersSourceCode, Encoding.UTF8));
        }

        private string GenerateSpecializedEnum(string namespaceName, string enumName, List<IFieldSymbol> members)
        {
            var builder = new StringBuilder();
            builder.AppendLine($@"// <auto-generated/>
#nullable enable

namespace {namespaceName}
{{
    /// <summary>
    /// Generated specialized enum based on base type
    /// </summary>
    public enum {enumName}
    {{");

            foreach (var member in members)
            {
                builder.AppendLine($"        {member.Name},");
            }

            builder.AppendLine(@"    }
}");

            return builder.ToString();
        }

        private string GenerateHelperClass(string namespaceName, string enumName, List<IFieldSymbol> members, List<string> prefixes)
        {
            var builder = new StringBuilder();
            builder.AppendLine($@"// <auto-generated/>
#nullable enable
using System;

namespace {namespaceName}
{{
    /// <summary>
    /// Helper methods for {enumName} enum
    /// </summary>
    public static class GameTypeHelpers
    {{");

            // Generate GetPlayerCount method
            builder.AppendLine($@"        /// <summary>
        /// Get the number of players for a game type
        /// </summary>
        public static int GetPlayerCount({enumName} gameType)
        {{
            return gameType switch
            {{");

            foreach (var member in members)
            {
                // Extract player count from name (e.g., "OneVOne" => 1, "TwoVTwo" => 2)
                int playerCount = 0;
                string memberName = member.Name;

                if (memberName.StartsWith("One"))
                    playerCount = 1;
                else if (memberName.StartsWith("Two"))
                    playerCount = 2;
                else if (memberName.StartsWith("Three"))
                    playerCount = 3;
                else if (memberName.StartsWith("Four"))
                    playerCount = 4;

                builder.AppendLine($"                {enumName}.{memberName} => {playerCount},");
            }

            builder.AppendLine($@"                _ => throw new ArgumentException($""Unknown game type: {{gameType}}"", nameof(gameType)),
            }};
        }}");

            // Generate GetDisplayName method
            builder.AppendLine($@"
        /// <summary>
        /// Get the display name for a game type
        /// </summary>
        public static string GetDisplayName({enumName} gameType)
        {{
            return gameType switch
            {{");

            foreach (var member in members)
            {
                // Try to get the display name from Display attribute, fallback to member name
                string displayName = GetDisplayNameFromAttributes(member) ?? member.Name;
                builder.AppendLine($"                {enumName}.{member.Name} => \"{displayName}\",");
            }

            builder.AppendLine($@"                _ => throw new ArgumentException($""Unknown game type: {{gameType}}"", nameof(gameType)),
            }};
        }}");

            // Generate conversion methods between enum types
            foreach (var sourcePrefix in prefixes)
            {
                var sourceEnumName = $"{sourcePrefix}GameType";

                foreach (var targetPrefix in prefixes.Where(p => p != sourcePrefix))
                {
                    var targetEnumName = $"{targetPrefix}GameType";

                    builder.AppendLine($@"
        /// <summary>
        /// Convert from {sourceEnumName} to {targetEnumName}
        /// </summary>
        public static {targetEnumName} To{targetEnumName}(this {sourceEnumName} gameType)
        {{
            return ({targetEnumName})gameType;
        }}");
                }
            }

            builder.AppendLine(@"    }
}");

            return builder.ToString();
        }

        private string? GetDisplayNameFromAttributes(IFieldSymbol member)
        {
            // Look for [Display(Name = "xxx")] attribute
            foreach (var attribute in member.GetAttributes())
            {
                if (attribute.AttributeClass?.Name == "DisplayAttribute" ||
                    attribute.AttributeClass?.ToDisplayString().EndsWith("DisplayAttribute") == true)
                {
                    // Try to get the Name property from named arguments
                    foreach (var namedArg in attribute.NamedArguments)
                    {
                        if (string.Equals(namedArg.Key, "Name", StringComparison.OrdinalIgnoreCase) &&
                            namedArg.Value.Value != null)
                        {
                            return namedArg.Value.Value.ToString();
                        }
                    }

                    // If no named arguments found, try the constructor arguments
                    if (attribute.ConstructorArguments.Length > 0 &&
                        attribute.ConstructorArguments[0].Value != null)
                    {
                        return attribute.ConstructorArguments[0].Value.ToString();
                    }
                }
            }

            // If no Display attribute was found or the Name property couldn't be extracted,
            // just return the member name as fallback
            return member.Name;
        }

        private class SyntaxReceiver : ISyntaxContextReceiver
        {
            public List<EnumToAugment> EnumsToAugment { get; } = new List<EnumToAugment>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                // We're only interested in enum declarations
                if (context.Node is EnumDeclarationSyntax enumDeclarationSyntax)
                {
                    // Get the semantic model for this enum
                    var enumSymbol = context.SemanticModel.GetDeclaredSymbol(enumDeclarationSyntax) as INamedTypeSymbol;
                    if (enumSymbol == null)
                        return;

                    // Look for the GenerateSpecializedEnums attribute
                    var attribute = enumSymbol.GetAttributes()
                        .FirstOrDefault(attr => attr.AttributeClass?.Name == "GenerateSpecializedEnumsAttribute");

                    if (attribute != null)
                    {
                        EnumsToAugment.Add(new EnumToAugment(enumSymbol, attribute, enumDeclarationSyntax));
                    }
                }
            }
        }

        private class EnumToAugment
        {
            public INamedTypeSymbol EnumSymbol { get; }
            public AttributeData AttributeData { get; }
            public EnumDeclarationSyntax EnumDeclaration { get; }

            public EnumToAugment(INamedTypeSymbol enumSymbol, AttributeData attributeData, EnumDeclarationSyntax enumDeclaration)
            {
                EnumSymbol = enumSymbol;
                AttributeData = attributeData;
                EnumDeclaration = enumDeclaration;
            }
        }
    }
}